### ISSUE TITLE
cannot import name 'Merge'

### ISSUE THREAD

**Issue by GrowthBreakthru** [junxuan-li/Learning-to-Minify-Photometric-Stereo#1]
![image](https://user-images.githubusercontent.com/46656578/105903857-6b2e8c80-5fee-11eb-9eca-8afe43ffc90d.png)
 
I am getting this error:  ImportError: cannot import name 'Merge'
I have tried installing all modules from Anaconda related to Keras in the environment for this project.

**Comment by junxuan-li** [comment]
Can you try changing the line 8 of file "pscnn_models.py" to:
> from keras.layers import Concatenate, concatenate, MaxPooling1D, multiply

I think I didn't use any model from Merge. I was using the "concatenate" module instead.

If it is still not working, try this link: [https://stackoverflow.com/questions/56315726/cannot-import-name-merge-from-keras-layers](https://stackoverflow.com/questions/56315726/cannot-import-name-merge-from-keras-layers)

**Comment by GrowthBreakthru** [comment]
Thank you for the reply Junxuan!

That seemed to fix the problem; however, I am now getting a lot of other errors. Most of them seem to be related to the installation of tensorflow. Also, the fact that my computer doesn't have an NVIDIA GPU may be causing a problem. 
![Minify problem](https://user-images.githubusercontent.com/46656578/106171920-288cc180-6160-11eb-9580-0dac025358ac.PNG)

On a separate note, I was wondering if you have any suggestions on how to load my own images from our Photometric Stereo camera setup into your PS algorithm? Also, do you know how to convert the .npy output files into a point cloud file or a 3D file for opening in Blender, CAD, or a different 3D viewer.

Sorry for so many questions. I am having a hard time finding answers to these questions online.

Thank you,
John High

**Comment by GrowthBreakthru** [comment]
Thank you for the reply Junxuan!

That seemed to fix that problem; however, I am getting a lot of other errors now. Most of these seem to be related to the installation of tensorflow. Also, the fact that my computer doesn't have a NVIDIA GPU may be causing a problem.
